on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🔨 Build Project
        env:
          VITE_REALM_APP: ${{ secrets.VITE_REALM_APP }}
          VITE_CLUSTER_NAME: ${{ secrets.VITE_CLUSTER_NAME }}
          VITE_DB_IMPORT_CALCULATOR: ${{ secrets.VITE_DB_IMPORT_CALCULATOR }}
          VITE_IMPORT_CALCULATOR_DATA: ${{ secrets.VITE_IMPORT_CALCULATOR_DATA }}
          VITE_IMPORT_CALCULATOR_HEADER: ${{ secrets.VITE_IMPORT_CALCULATOR_HEADER }}
        run: |
          npm install
          npm run build
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
